### PR TITLE
Vanilla cURL 8.10.0

### PR DESCRIPTION
**Pull request by cmb69**
Untested build: https://github.com/winlibs/winlib-builder/actions/runs/10810226257

Probably pretty useless to test this build, since it doesn't fetch the latest nghttp2 and libssh2 updates. I'll think about some improvements.

### CODE REVIEW

**Comment by ndossche** [comment]
Right... The previous time I updated Curl I had a mirror set up of the deps + series files and pointed a fork of winlib-builder to that. It's pretty cumbersome though and I wouldn't recommend that to anyone. Anyway, I guess this PR is good to go, can't think of anything special that needs to be done here.

**Comment by Jan-E** [comment]
If you’ve got a build environment ready with all the deps it is not cumbersome at all. I started a batch file and waited until all versions were built. VC9 x86 & x64, VC11 idem, VC14 with 2 OpenSSL versions, VC15, VS16 with 2 OpenSSL versions. All versions linked with OpenSSL and with Schannel. 28 different combinations or something like that.

**Comment by cmb69** [comment]
I guess we should wait for [cURL 8.10.1](https://curl.se/mail/lib-2024-09/0013.html).

> If you’ve got a build environment ready with all the deps it is not cumbersome at all.

Well, it's doable one way or another, but you need to fetch the dependencies somehow, and can't just use phpsdk_deps (or other automation which looks at the official series files).

**Comment by cmb69** [comment]
Superseded by #24.

**Pull request closed without merging**
