### PR TITLE
Vanilla cURL 8.10.1

### PR DESCRIPTION
**Pull request by cmb69**
Yet untested build: https://github.com/winlibs/winlib-builder/actions/runs/10919955697

AFK for now, but planning to test with latest dependencies (libssh2, nghttp2) in a few hours.

### CODE REVIEW

**Comment by Jan-E** [comment]
Will you be using libssh2 from Git head or the latest release? There are loads of commits after 1.11.0 including some fixing CVE's but a new release got stuck somewhere. See https://github.com/libssh2/libssh2/discussions/1249#discussioncomment-9157679

**Comment by cmb69** [comment]
@Jan-E, thank for the information! I was planning to go with https://github.com/winlibs/libssh2/pull/5, but that might not be the best idea.

**Comment by cmb69** [comment]
So, for what it's worth, I've used the PHP-8.3 builds of https://github.com/winlibs/libssh2/pull/5 and https://github.com/winlibs/nghttp2/pull/2 to build PHP 8.4 against libcurl 8.10.1 (x64 and x86), and didn't notice any issues when running the test suite. Maybe it makes sense to roll out these builds for 8.4 and master, and then to have a look at the libssh2 issue [mentioned by Jan, above](https://github.com/winlibs/cURL/pull/24#issuecomment-2358216652).

@shivammathur, thoughts?

**Comment by shivammathur** [comment]
Yes, we can update this and look at libssh2 next.

**Comment by shivammathur** [comment]
@cmb69 Uploaded and updated staging series files for 8.4 and master.

**Comment by cmb69** [comment]
libssh2 1.11.1 update available as https://github.com/winlibs/libssh2/pull/6.

**Pull request merged**
